#!/bin/bash
# Setup GitHub Secrets for SSH-based deployment
# Run this to configure secrets in your GitHub repository

echo "🔐 GitHub Secrets Setup"
echo "======================================"
echo ""
echo "Necesita agregar estos secrets a su repositorio:"
echo ""
echo "1. SSH_PRIVATE_KEY"
echo "   → Encoding: base64 del contenido de labsuser.pem"
echo "   → Generar con:"
echo "      cat ~/.ssh/labsuser.pem | base64 -w0"
echo ""
echo "2. ANALYTICS_INSTANCE_IP (opcional)"
echo "   → La IP de EC2-Analytics cuando esté disponible"
echo ""
echo "3. SLACK_WEBHOOK (opcional)"
echo "   → URL del webhook de Slack para notificaciones"
echo ""
echo "======================================"
echo "Pasos en GitHub:"
echo "======================================"
echo "1. Ve a: Settings → Secrets and variables → Actions"
echo "2. Click 'New repository secret'"
echo "3. Agrega cada secret con su nombre y valor"
echo ""
echo "Genera SSH_PRIVATE_KEY:"
echo "$ cat ~/.ssh/labsuser.pem | base64 -w0 | pbcopy"
echo ""
echo "✅ Una vez agregados los secrets, los workflows funcionarán automáticamente"
echo ""
